services:
  database:
    image: postgres:16
    container_name: clinica_database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clinica_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  users_service:
    build: ./users_service
    container_name: clinica_users_service
    restart: on-failure
    depends_on:
      - database
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=clinica_db

      - GRPC_PORT=50051
      
  users_client:
    build:
      context: ./clients
      dockerfile: users_client/Dockerfile
    image: filipefernandes/users-client:v1
    container_name: clinica_users_client
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    depends_on:
      - users_service
    environment:
      - GRPC_ADDRESS=users_service:50051
    volumes:
      - ./client_data:/root/.med_session
      
volumes:
  postgres_data: